### ISSUE TITLE
Kegberry Controller not recognized

### ISSUE THREAD

**Issue by itnetworksolutions** [Kegbot/kegberry#18]
I purchased the single tap Kegbot kit and used a raspberry pi to host the server.  I have tried building it from scratch (doing every step manually) and by using the Wheezy Raspbian image from kegberry.com.  Both times I was able to host the server successfully, but the Kegboard would never register as a controller.  All the lights come on and the flow meter appears to work correctly according to the board, however, it will not communicate with my pi which it is directly plugged into via USB.  Any ideas?

**Comment by itnetworksolutions** [comment]
No love?

**Comment by mik3y** [comment]
Hey there - sorry, I've been traveling and unable to look at this. I will follow up this weekend. In the meantime have you asked around on the Kegbot forum? Might be some folks who can help.

**Comment by itnetworksolutions** [comment]
I’ve asked at Kegberry.com but received no reply.  I have seen similar posts on kegbot but no answers

**Comment by mik3y** [comment]
Can you try the following:
* Boot the pi
* Plug in the kegboard
* Wait a few seconds, then run the command: `sudo lsusb`
* Paste the output here when done.

We're also preparing a new release; not aware of any known issues here, but, it's a good time to debug this in case we find one.

**Comment by itnetworksolutions** [comment]
Bus 001 Device 002: ID 0424:9512 Standard Microsystems Corp.

Bus 001 Device 001: ID 1d6b:002 Linux Foundation 2.0 root hub

Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp.

Bus 001 Device 005: ID 03eb:0436 Atmel Corp.

Bus 001 Device 004: ID 0d62:2106 Darfon Electronics Corp. Dell L20U Multimedia Keyboard

**Comment by itnetworksolutions** [comment]
OK!  I feel like i'll be on my own here... How do I return the single tap kit?  I'll

**Comment by itnetworksolutions** [comment]
I have another Raspberry Pi (this one is a B+ version).  I downloaded a fresh install of the image and burned the img file to sd card.  After initial config, I could load the software through a web browser but this also would not recognize the controller...

**Comment by mik3y** [comment]
Hey, I think we have two topics going on this, one here and one on the forum.  Forum is awaiting your reply, so I'll close this and continue there.

**Comment by itnetworksolutions** [comment]
Could find a post with my name on forum so.....

I have seen others with similar problem...  This gift is now 2 months old and still not working for my father..

At this point, I just want to return.


Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by mik3y** [comment]
Oh, sorry. Sometimes people use different handles, I believed I was it was the same person.

Mail us at support@bevbot.com and we can continue troubleshooting, or arrange a return.

**Comment by mik3y** [comment]
By the way, I'm sure we can get you up and running — the biggest issue is that we need to release a new version of the preinstalled image.  The steps in the forum get you there, but if you have any patience left, we should be able to turn a new image out tonight.

I'm very sorry you've had a bad experience, it's not typical and not acceptable.

**Comment by itnetworksolutions** [comment]
I'm sorry, i do not want to have to return the product.  I had noticed a few similar problems on the forum but I guess I haven't found the thread with the working solution.  I am going out of town tomorrow but will try the new image when  I return Sunday.   

Thanks


Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by mik3y** [comment]
Don't sweat it! The whole point of Kegberry is to make install trivial, and we've clearly missed the mark here.  Hit me up here or on support@ Sunday and we'll get you sorted!

**Comment by itnetworksolutions** [comment]
The same version is still showing on the download page.  Is there a special link to get the latest image?


Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by mik3y** [comment]
Let's move the discussion over to [this forum thread](https://forum.kegbot.org/t/kegboard-not-showing-up-kegberry/344/20), since there are others in the same situation & should have the same fix. There is a link to a new image there, too. Thanks.
