### ISSUE TITLE
redis/celery 

### ISSUE THREAD

**Issue by thehijjt** [Kegbot/kegberry#19]
I had an issue with a fresh install today of kegberry server. 
bash -c "$(curl -fsSL https://raw.github.com/Kegbot/kegberry/master/install.sh)"
Went through without any issues, and the setup web page went through without issues, however when I went to kegadmin page, I was presented with a 500 error. (Debug was set to False). I then set debug to true, and noticed that the errors were related to redis
**init**() got an unexpected keyword argument 'socket_connect_timeout'
Searching for that noted that there is an error in redis with celery/

I fixed the error by calling : 
pip install -U celery[redis]
in the virtual environment for kegbot-server.

Everything that I have tested after has worked.

**Comment by mik3y** [comment]
(Closing age-old issue, and should be fixed in #21 - thanks!)
